### ISSUE TITLE
Deeplinks

### ISSUE THREAD

**Issue by joeblew99** [sidinaz/routex#1]
This looks pretty good for our project.

We have lots of modules which themselves have routes. They are then imported by the main app.

Have you tried to see if this also works with deeplinks like what the unilinks plugin supports.

**Comment by sidinaz** [comment]
If you plan to use uni_links getLinksStream() as single emitting stream in handler maybe you are on right path .
See ExamplesSource and ExampleController(in example app folder of this repo) for examples with standalone router.
RoutexNavigator is just wrapper for interacting with router. Maybe that can give you some better idea how can you integrate framework with deep links functionality.

Can you provide more info, please?
It can be useful for some further scenarios.
